name: Deploy SNAPSHOT to Sonatype

on:
  # Pemicu: Jalankan setiap kali ada push ke branch 'main'
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Konfigurasi server tetap sama
          server-id: ossrh 
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          # Kita tidak perlu GPG untuk snapshot
          # jadi tidak perlu menambahkan gpg-private-key & gpg-passphrase di sini cobax

      - name: Publish SNAPSHOT to Sonatype
        # Perintahnya lebih sederhana, tanpa '-P release'
        # Pastikan versi di pom.xml berakhiran -SNAPSHOT
        run: mvn --batch-mode deploy