name: Build and Deploy with GPG Signing

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Langkah Kunci 1: Impor kunci GPG seperti sebelumnya
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Langkah Kunci 2: Jalankan Maven dengan argumen GPG
      # Perhatikan penambahan -Dgpg.keyname dan -Dgpg.passphrase
      - name: Build and Deploy with Maven
        run: |
          mvn -B deploy -P release \
            -Dgpg.keyname=${{ steps.import_gpg.outputs.keyid }} \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          # Jika Anda mendeploy ke Maven Central atau repositori lain
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}